[package]
name = "algostructures"
version = "0.1.0"
authors = ["Michael Suggs <suggs.michael.jeffrey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2"
rand = "0.8.3"
snafu = "0.6.10"
